# Generated by Django 5.0.6 on 2024-06-10 13:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("63362bb3-79c1-4ca4-98eb-1d0044016e74"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userconfirmation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("63362bb3-79c1-4ca4-98eb-1d0044016e74"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
