# Generated by Django 5.0.6 on 2024-06-24 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_id_alter_userconfirmation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d123bee2-11fc-4bad-9200-0790f359e6ab"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userconfirmation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d123bee2-11fc-4bad-9200-0790f359e6ab"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
