# Generated by Django 5.0.6 on 2024-06-24 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_id_alter_userconfirmation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c62f3443-e7ff-4414-9a00-d04434a1b718"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="userconfirmation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c62f3443-e7ff-4414-9a00-d04434a1b718"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
