# Generated by Django 5.0.6 on 2024-06-24 12:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentlike",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c62f3443-e7ff-4414-9a00-d04434a1b718"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c62f3443-e7ff-4414-9a00-d04434a1b718"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="postcomment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c62f3443-e7ff-4414-9a00-d04434a1b718"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c62f3443-e7ff-4414-9a00-d04434a1b718"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
